[project]
name = "site-forum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Squilix", email = "Squilix01@no-reply.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django==5.2",
    "django-filter>=26.1",
    "djangorestframework>=3.18.0",
    "drf-spectacular>=0.30.0",
    "markdown>=3.10.3",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
]

[project.scripts]
site-forum = "site_forum:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
